<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!--General parameters-->
    <xacro:property name="PI" value="3.1415926535897931"/>

    <!--Puzzlebot parameters-->
        <!--General parameters-->
            <xacro:property name="wheel_base_distance" value="0.19"/>

    <!--Chassis-->
        <!--Chassis Inertial/Collision parameters-->
            <xacro:property name="chassis_mass" value="0.351"/>
            <xacro:property name="chassis_length" value="0.2"/>
            <xacro:property name="chassis_width" value="0.16"/>
            <xacro:property name="chassis_height" value="0.0503"/>

            <xacro:property name="chassis_inertia_pos_x" value="0.00"/>
            <xacro:property name="chassis_inertia_pos_y" value="0.0"/>
            <xacro:property name="chassis_inertia_pos_z" value="0.00"/>
            <xacro:property name="chassis_inertia_pos_r" value="0.00"/>
            <xacro:property name="chassis_inertia_pos_p" value="0.0"/>
            <xacro:property name="chassis_inertia_pos_w" value="0.0"/>

            <xacro:property name="chassis_collision_pos_x" value="0.0"/>
            <xacro:property name="chassis_collision_pos_y" value="0.0"/>
            <xacro:property name="chassis_collision_pos_z" value="0.0"/>
            <xacro:property name="chassis_collision_pos_r" value="0.0"/>
            <xacro:property name="chassis_collision_pos_p" value="0.0"/>
            <xacro:property name="chassis_collision_pos_w" value="0.0"/>

        <!--Chassis Visual parameters-->
            <xacro:property name="chassis_mesh_pos_x" value="0.0"/>
            <xacro:property name="chassis_mesh_pos_y" value="0.0"/>
            <xacro:property name="chassis_mesh_pos_z" value="0.0"/>
            <xacro:property name="chassis_mesh_pos_r" value="${PI/2}"/>
            <xacro:property name="chassis_mesh_pos_p" value="0.0"/>
            <xacro:property name="chassis_mesh_pos_w" value="${PI/2}"/>

        <!--Chassis Joint parameters-->
            <xacro:property name="chassis_pos_x" value="-0.052"/>
            <xacro:property name="chassis_pos_y" value="0.0"/>
            <xacro:property name="chassis_pos_z" value="0.05"/>
            <xacro:property name="chassis_pos_r" value="0.0"/>
            <xacro:property name="chassis_pos_p" value="0.0"/>
            <xacro:property name="chassis_pos_w" value="0.0"/>

    <!--Caster Holder-->
        <!--Caster Holder Inertial/Collision parameters-->
            <xacro:property name="casterholder_mass" value="0.007"/>
            <xacro:property name="casterholder_length" value="0.0175"/>
            <xacro:property name="casterholder_width" value="0.023"/>
            <xacro:property name="casterholder_height" value="0.011150"/>

            <xacro:property name="casterholder_inertia_pos_x" value="0.0"/>
            <xacro:property name="casterholder_inertia_pos_y" value="0.0"/>
            <xacro:property name="casterholder_inertia_pos_z" value="0.0"/>
            <xacro:property name="casterholder_inertia_pos_r" value="0.0"/>
            <xacro:property name="casterholder_inertia_pos_p" value="0.0"/>
            <xacro:property name="casterholder_inertia_pos_w" value="0.0"/>

            <xacro:property name="casterholder_collision_pos_x" value="0.0"/>
            <xacro:property name="casterholder_collision_pos_y" value="0.0"/>
            <xacro:property name="casterholder_collision_pos_z" value="0.0"/>
            <xacro:property name="casterholder_collision_pos_r" value="0.0"/>
            <xacro:property name="casterholder_collision_pos_p" value="0.0"/>
            <xacro:property name="casterholder_collision_pos_w" value="0.0"/>

        <!--Caster Holder Visual parameters-->
            <xacro:property name="casterholder_mesh_pos_x" value="0.0"/>
            <xacro:property name="casterholder_mesh_pos_y" value="0.0"/>
            <xacro:property name="casterholder_mesh_pos_z" value="-0.0065"/>
            <xacro:property name="casterholder_mesh_pos_r" value="0.0"/>
            <xacro:property name="casterholder_mesh_pos_p" value="0.0"/>
            <xacro:property name="casterholder_mesh_pos_w" value="0.0"/>

        <!--Caster Holder Joint parameters-->
            <xacro:property name="casterholder_pos_x" value="-0.095"/>
            <xacro:property name="casterholder_pos_y" value="0.0"/>
            <xacro:property name="casterholder_pos_z" value="-0.030725"/>
            <xacro:property name="casterholder_pos_r" value="0.0"/>
            <xacro:property name="casterholder_pos_p" value="0.0"/>
            <xacro:property name="casterholder_pos_w" value="0.0"/>

    <!--Caster Ball-->
        <!--Caster Ball Inertial/Collision parameters-->
            <xacro:property name="casterball_mass" value="0.009"/>
            <xacro:property name="casterball_radius" value="0.0065"/>

            <xacro:property name="casterball_inertia_pos_x" value="0.0"/>
            <xacro:property name="casterball_inertia_pos_y" value="0.0"/>
            <xacro:property name="casterball_inertia_pos_z" value="0.0"/>
            <xacro:property name="casterball_inertia_pos_r" value="0.0"/>
            <xacro:property name="casterball_inertia_pos_p" value="0.0"/>
            <xacro:property name="casterball_inertia_pos_w" value="0.0"/>

            <xacro:property name="casterball_collision_pos_x" value="0.0"/>
            <xacro:property name="casterball_collision_pos_y" value="0.0"/>
            <xacro:property name="casterball_collision_pos_z" value="0.0"/>
            <xacro:property name="casterball_collision_pos_r" value="0.0"/>
            <xacro:property name="casterball_collision_pos_p" value="0.0"/>
            <xacro:property name="casterball_collision_pos_w" value="0.0"/>

        <!--Caster Ball Visual parameters-->
            <xacro:property name="casterball_mesh_pos_x" value="0.0"/>
            <xacro:property name="casterball_mesh_pos_y" value="0.0"/>
            <xacro:property name="casterball_mesh_pos_z" value="0.0"/>
            <xacro:property name="casterball_mesh_pos_r" value="0.0"/>
            <xacro:property name="casterball_mesh_pos_p" value="0.0"/>
            <xacro:property name="casterball_mesh_pos_w" value="0.0"/>

        <!--Caster Ball Joint parameters-->
            <xacro:property name="casterball_pos_x" value="0.0"/>
            <xacro:property name="casterball_pos_y" value="0.0"/>
            <xacro:property name="casterball_pos_z" value="-0.012538"/>
            <xacro:property name="casterball_pos_r" value="0.0"/>
            <xacro:property name="casterball_pos_p" value="0.0"/>
            <xacro:property name="casterball_pos_w" value="0.0"/>

    <!--Wheel-->
        <!--Wheel Inertial/Collision parameters-->
            <xacro:property name="wheel_mass" value="0.027"/>
            <xacro:property name="wheel_height" value="0.005"/>
            <xacro:property name="wheel_radius" value="0.05"/>

            <xacro:property name="wheel_inertia_pos_x" value="0.0"/>
            <xacro:property name="wheel_inertia_pos_y" value="0.0"/>
            <xacro:property name="wheel_inertia_pos_z" value="0.0"/>
            <xacro:property name="wheel_inertia_pos_r" value="0.0"/>
            <xacro:property name="wheel_inertia_pos_p" value="0.0"/>
            <xacro:property name="wheel_inertia_pos_w" value="0.0"/>

            <xacro:property name="wheel_collision_pos_x" value="0.0"/>
            <xacro:property name="wheel_collision_pos_y" value="0.0"/>
            <xacro:property name="wheel_collision_pos_z" value="0.0"/>
            <xacro:property name="wheel_collision_pos_r" value="0.0"/>
            <xacro:property name="wheel_collision_pos_p" value="0.0"/>
            <xacro:property name="wheel_collision_pos_w" value="0.0"/>

        <!--Wheel Visual parameters-->
            <xacro:property name="wheel_mesh_pos_x" value="0.0"/>
            <xacro:property name="wheel_mesh_pos_y" value="0.0"/>
            <xacro:property name="wheel_mesh_pos_z" value="0.0"/>
            <xacro:property name="wheel_mesh_pos_r" value="0.0"/>
            <xacro:property name="wheel_mesh_pos_p" value="${PI/2}"/>
            <xacro:property name="wheel_mesh_pos_w" value="0.0"/>

        <!--Wheel Joint parameters-->
            <xacro:property name="wheel_pos_x" value="0.052"/>
            <xacro:property name="wheel_pos_y" value="${wheel_base_distance/2}"/>
            <xacro:property name="wheel_pos_z" value="0.0"/>
            <xacro:property name="wheel_pos_r" value="${PI/2}"/>
            <xacro:property name="wheel_pos_p" value="0.0"/>
            <xacro:property name="wheel_pos_w" value="0.0"/>


    <!--Motor-->
        <!--Motor Inertial/Collision parameters-->
            <xacro:property name="motor_mass" value="0.1"/>
            <xacro:property name="motor_height" value="0.06645"/>
            <xacro:property name="motor_radius" value="0.0125"/>

            <xacro:property name="motor_inertia_pos_x" value="0.0"/>
            <xacro:property name="motor_inertia_pos_y" value="0.00825"/>
            <xacro:property name="motor_inertia_pos_z" value="0.0"/>
            <xacro:property name="motor_inertia_pos_r" value="${PI/2}"/>
            <xacro:property name="motor_inertia_pos_p" value="0.0"/>
            <xacro:property name="motor_inertia_pos_w" value="0.0"/>

            <xacro:property name="motor_collision_pos_x" value="0.0"/>
            <xacro:property name="motor_collision_pos_y" value="0.0"/>
            <xacro:property name="motor_collision_pos_z" value="0.0"/>
            <xacro:property name="motor_collision_pos_r" value="${PI/2}"/>
            <xacro:property name="motor_collision_pos_p" value="0.0"/>
            <xacro:property name="motor_collision_pos_w" value="0.0"/>

        <!--Motor Visual parameters-->
            <xacro:property name="motor_mesh_pos_x" value="0.0"/>
            <xacro:property name="motor_mesh_pos_y" value="0.009"/>
            <xacro:property name="motor_mesh_pos_z" value="0.0"/>
            <xacro:property name="motor_mesh_pos_r" value="0.0"/>
            <xacro:property name="motor_mesh_pos_p" value="0.0"/>
            <xacro:property name="motor_mesh_pos_w" value="${PI/2}"/>

        <!--Motor Joint parameters-->
            <xacro:property name="motor_pos_x" value="0.052"/>
            <xacro:property name="motor_pos_y" value="0.038775"/>
            <xacro:property name="motor_pos_z" value="0.0"/>
            <xacro:property name="motor_pos_r" value="0.0"/>
            <xacro:property name="motor_pos_p" value="0.0"/>
            <xacro:property name="motor_pos_w" value="0.0"/>

    <!--Powerbank-->
        <!--Powerbank Inertial/Collision parameters-->
            <xacro:property name="powerbank_mass" value="0.203"/>
            <xacro:property name="powerbank_length" value="0.13"/>
            <xacro:property name="powerbank_width" value="0.07"/>
            <xacro:property name="powerbank_height" value="0.012"/>

            <xacro:property name="powerbank_inertia_pos_x" value="0.0"/>
            <xacro:property name="powerbank_inertia_pos_y" value="0.0"/>
            <xacro:property name="powerbank_inertia_pos_z" value="0.0"/>
            <xacro:property name="powerbank_inertia_pos_r" value="0.0"/>
            <xacro:property name="powerbank_inertia_pos_p" value="0.0"/>
            <xacro:property name="powerbank_inertia_pos_w" value="0.0"/>

            <xacro:property name="powerbank_collision_pos_x" value="0.0"/>
            <xacro:property name="powerbank_collision_pos_y" value="0.0"/>
            <xacro:property name="powerbank_collision_pos_z" value="0.0"/>
            <xacro:property name="powerbank_collision_pos_r" value="0.0"/>
            <xacro:property name="powerbank_collision_pos_p" value="0.0"/>
            <xacro:property name="powerbank_collision_pos_w" value="0.0"/>

        <!--Powerbank Visual parameters-->
            <xacro:property name="powerbank_mesh_pos_x" value="0.0"/>
            <xacro:property name="powerbank_mesh_pos_y" value="0.0"/>
            <xacro:property name="powerbank_mesh_pos_z" value="0.0"/>
            <xacro:property name="powerbank_mesh_pos_r" value="${PI/2}"/>
            <xacro:property name="powerbank_mesh_pos_p" value="0.0"/>
            <xacro:property name="powerbank_mesh_pos_w" value="${PI/2}"/>

        <!--Powerbank Joint parameters-->
            <xacro:property name="powerbank_pos_x" value="0.03"/>
            <xacro:property name="powerbank_pos_y" value="0.00"/>
            <xacro:property name="powerbank_pos_z" value="0.01415"/>
            <xacro:property name="powerbank_pos_r" value="0.0"/>
            <xacro:property name="powerbank_pos_p" value="0.0"/>
            <xacro:property name="powerbank_pos_w" value="0.0"/>



    <!--Meshes -->
        <xacro:property name="mesh_puzzlebot_chassis"  value="$(find puzzlebot_description)/meshes/bases/MCR2_puzzlebot_chassis_v1_2.stl" />
        <xacro:property name="mesh_puzzlebot_motor_left"  value="$(find puzzlebot_description)/meshes/misc/MCR2_dc_motor_left.stl" />
        <xacro:property name="mesh_puzzlebot_motor_right"  value="$(find puzzlebot_description)/meshes/misc/MCR2_dc_motor_right.stl" />
        <xacro:property name="mesh_puzzlebot_wheel"  value="$(find puzzlebot_description)/meshes/wheels/MCR2_puzzlebot_wheel.stl" />
        <xacro:property name="mesh_puzzlebot_caster"  value="$(find puzzlebot_description)/meshes/wheels/MCR2_puzzlebot_casterball.stl" />
        <xacro:property name="mesh_puzzlebot_battery"  value="$(find puzzlebot_description)/meshes/misc/MCR2_puzzlebot_battery.stl" />
 
</robot>