base_controller:
  type        : "diff_drive_controller/DiffDriveController"
  left_wheel  : 'wheel_left_joint'
  right_wheel : 'wheel_right_joint'

  publish_rate: 50.0               # default: 50

  pose_covariance_diagonal : [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]

  # Odometry is published by robot_localization, so
  # no need to publish a TF. Use only for testing
  enable_odom_tf: false
  odom_frame_id: "world"
  # Base frame_id
  base_frame_id: /base_link #default: base_link

  # Wheel separation and diameter. These are both optional.
  # diff_drive_controller will attempt to read either one or both from the
  # URDF if not specified as a parameter
  wheel_separation : 0.19
  wheel_radius : 0.050

  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1.0 # default: 1.0
  wheel_radius_multiplier    : 1.0 # default: 1.0

  #Publish the velocity command to be executed. It is to monitor the effect of limiters on the controller input.
  publish_cmd: false

  # Velocity commands timeout [s], default 0.5
  cmd_vel_timeout: 0.5

  #Setting this to true will allow more than one publisher on the input topic
  allow_multiple_cmd_vel_publishers: true

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 0.60  # m/s
      min_velocity           : -0.60 # m/s
      has_acceleration_limits: true
      max_acceleration       : 2.6  # m/s^2
      min_acceleration       : -2.6 # m/s^2

  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 3.1  # rad/s
      has_acceleration_limits: true
      max_acceleration       : 2.6  # rad/s^2
